# QLoRA Training Configuration
  log_freq: 50
  seed: 42

  distributed: False
  dist_url: "env://"
  world_size: 1
  device: cuda

  resume_ckpt_path: null
  output_dir: output/microvlm_qlora

  amp: True

  accum_grad_iters: 4  # Effective batch size = 32
  iters_per_epoch: 2000
  num_workers: 4
  batch_size: 8
  max_epoch: 3
  weight_decay: 0.01

  warmup_steps: 500
  warmup_lr: 1e-6
  min_lr: 1e-5
  init_lr: 2e-4
  lr_sched: linear_warmup_cosine_lr
  # Optimizer - lower LR for QLoRA

  runner: runner_base
  task: image_text_pretrain
run:

    sample_ratio: 100
        name: blip_caption
      train:
    text_processor:
        image_size: 224
        name: blip2_image_train
      train:
    vis_processor:
    batch_size: 8
  coco_caption:
datasets:

  device_8bit: 0
  low_resource: False
  # Resource settings

  lora_dropout: 0.05
  lora_alpha: 16
  lora_r: 64
  use_qlora: True  # Enable 4-bit quantization
  use_lora: True
  max_context_len: 2048
  max_txt_len: 512
  llm_model: "Qwen/Qwen2.5-0.5B"
  # LLM with QLoRA (4-bit quantization + LoRA)

  freeze_qformer: False
  cross_attention_freq: 2
  qformer_num_layers: 6
  qformer_hidden_size: 768
  num_query_token: 32
  # Q-Former - trainable

  freeze_vit: True
  vit_precision: fp16
  use_grad_checkpoint: True
  drop_path_rate: 0
  image_size: 224
  vision_encoder: diet_tiny
  # Vision encoder - frozen

  ckpt: ""  # Set to previous checkpoint if resuming
  model_type: default
  arch: microvlm
model:

# Uses 4-bit quantization with LoRA for memory-efficient training

