# Stage 2: Adapter (LoRA/QLoRA) Training
# Trains: Q-Former, Projection layers, LoRA adapters
# Frozen: Vision encoder, LLM base weights

model:
  arch: microvlm
  model_type: default
  ckpt: ""  # Set to stage 1 checkpoint

  # Vision encoder - frozen
  vision_encoder: diet_tiny
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: True
  vit_precision: fp16
  freeze_vit: True

  # Q-Former - trainable
  num_query_token: 32
  qformer_hidden_size: 768
  qformer_num_layers: 6
  cross_attention_freq: 2
  freeze_qformer: False

  # LLM with LoRA
  llm_model: "Qwen/Qwen2.5-0.5B"
  max_txt_len: 256
  max_context_len: 2048
  use_lora: True
  use_qlora: False
  lora_r: 64
  lora_alpha: 16
  lora_dropout: 0.05

datasets:
  laion:
    batch_size: 32
    vis_processor:
      train:
        name: blip2_image_train
        image_size: 224
    text_processor:
      train:
        name: blip_caption
    sample_ratio: 115

  cc_sbu:
    batch_size: 32
    vis_processor:
      train:
        name: blip2_image_train
        image_size: 224
    text_processor:
      train:
        name: blip_caption
    sample_ratio: 14

run:
  task: image_text_pretrain
  runner: runner_base

  # Optimizer
  lr_sched: linear_warmup_cosine_lr
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6
  warmup_steps: 5000

  weight_decay: 0.05
  max_epoch: 4
  batch_size: 32
  num_workers: 4
  iters_per_epoch: 5000
  accum_grad_iters: 2

  amp: True

  output_dir: output/microvlm_stage2
  resume_ckpt_path: null

  device: cuda
  world_size: 1
  dist_url: "env://"
  distributed: True

  seed: 42
  log_freq: 50

