# Stage 1: Basic Image-Text Feature Alignment
# Trains: Q-Former, Projection layers
# Frozen: Vision encoder, LLM (no LoRA yet)

model:
  arch: microvlm
  model_type: default
  vision_encoder: diet_tiny
  image_size: 224
  drop_path_rate: 0
  use_grad_checkpoint: False
  vit_precision: fp16
  freeze_vit: True
  num_query_token: 32
  qformer_hidden_size: 768
  qformer_num_layers: 6
  cross_attention_freq: 2
  freeze_qformer: False
  llm_model: "Qwen/Qwen2.5-0.5B"
  max_txt_len: 128
  max_context_len: 2048
  use_lora: False
  use_qlora: False

datasets:
  coco_caption:
    batch_size: 32
    vis_processor:
      train:
        name: blip2_image_train
        image_size: 224
    text_processor:
      train:
        name: blip_caption
    sample_ratio: 100

run:
  task: image_text_pretrain
  runner: runner_base
  lr_sched: linear_warmup_cosine_lr
  init_lr: 1e-4
  min_lr: 8e-5
  warmup_lr: 1e-6
  warmup_steps: 1000
  weight_decay: 0.05
  max_epoch: 1
  batch_size: 32
  num_workers: 4
  iters_per_epoch: 5000
  accum_grad_iters: 1
  amp: True
  output_dir: output/microvlm_stage1
  device: cuda
  distributed: False
  seed: 42
  log_freq: 50
