# Stage 4: Multi-Task Fine-Tuning

model:
  arch: microvlm
  model_type: default
  ckpt: ""
  vision_encoder: diet_tiny
  image_size: 448
  drop_path_rate: 0
  use_grad_checkpoint: True
  vit_precision: fp16
  freeze_vit: True
  num_query_token: 32
  qformer_hidden_size: 768
  qformer_num_layers: 6
  cross_attention_freq: 2
  freeze_qformer: False
  llm_model: "Qwen/Qwen2.5-0.5B"
  max_txt_len: 1024
  max_context_len: 3800
  end_sym: "###"
  use_lora: True
  use_qlora: False
  lora_r: 64
  lora_alpha: 16
  lora_dropout: 0.05

datasets:
  coco_caption:
    batch_size: 4
    vis_processor:
      train:
        name: blip2_image_train
        image_size: 448
    text_processor:
      train:
        name: blip_caption
    sample_ratio: 100

run:
  task: multi_task
  runner: runner_base
  lr_sched: linear_warmup_cosine_lr
  init_lr: 2e-5
  min_lr: 5e-6
  warmup_lr: 1e-6
  warmup_steps: 500
  weight_decay: 0.05
  max_epoch: 3
  batch_size: 4
  num_workers: 4
  iters_per_epoch: 3000
  accum_grad_iters: 4
  amp: True
  output_dir: output/microvlm_stage4
  resume_ckpt_path: null
  device: cuda
  distributed: False
  seed: 42
  log_freq: 20
