# Evaluation configuration for MicroVLM-E

model:
  arch: microvlm
  ckpt: ""
  vision_encoder: diet_tiny
  image_size: 224
  freeze_vit: True
  num_query_token: 32
  qformer_hidden_size: 768
  qformer_num_layers: 6
  llm_model: "Qwen/Qwen2.5-0.5B"
  max_txt_len: 512
  max_context_len: 2048
  use_lora: True
  lora_r: 64
  lora_alpha: 16

evaluation:
  max_new_tokens: 256
  min_length: 1
  temperature: 0.7
  top_p: 0.9
  do_sample: False
  num_beams: 5
  tasks:
    - vqa
    - captioning
    - grounding

run:
  device: cuda
  batch_size: 8
  num_workers: 4
  output_dir: eval_results
